language: php
php:
  - 7.0
  - 7.1
  - 7.2
sudo: false
services:
  - mysql
  - postgresql
  - memcached
  - mongodb
before_install:
  - phpenv config-add tests/config.ini
  - phpenv config-rm xdebug.ini
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database fusio;'; fi;
  - if [ $DB = 'pgsql' ]; then psql -c 'create database fusio;' -U postgres; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
