name: CI
on:
  - pull_request
  - push
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run Psalm
        run: vendor/bin/psalm --no-progress --shepherd --show-info=false --stats
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }}-${{ matrix.database }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
        database:
          - sqlite
          - mysql
          - postgres
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: test1234
          MYSQL_DATABASE: fusio
        ports:
          - 33306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: fusio
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Wait for
        run: DB=${{ matrix.database }} php bin/fusio system:wait_for
      - name: Run PHPUnit
        run: DB=${{ matrix.database }} vendor/bin/phpunit
